### ISSUE TITLE
Use mold indicator as a template for fixing double updates

### ISSUE THREAD

**Issue by tetsuo55** [lymanepp/thermal_comfort#5]
The mold indicator component does the same thing we do, read temperature and humidity to calculate dew point.

We should try to rebase the way we read and process the sensors inputs on it

https://github.com/home-assistant/core/blob/dev/homeassistant/components/mold_indicator/sensor.py

**Comment by tetsuo55** [comment]
Yes that's the one.

Its easy to reproduce.

Install the sqlweb addon.
Open the web ui
Click on events
Click on query
Insert this command, replace the sensor with your absolutehumidity sensor
`select state, created from states WHERE entity_id = 'sensor.ferres_timestamp_delta' ORDER by state_id DESC LIMIT 10;`

You should see most updates being logged twice a few milliseconds apart

![IMG_20210922_222016](https://user-images.githubusercontent.com/15817790/134415993-b45cd646-65e5-405c-9a9c-ebf0cdd2d786.jpg)

**Comment by lymanepp** [comment]
Gotcha. I'm looking at the mold indicator implementation now.

**Comment by lymanepp** [comment]
My refactored implementation uses this approach. Let me know how it looks.

**Comment by tetsuo55** [comment]
Oof that was a breaking change, had to rename all the sensors, the new naming seems better tho, readme will have to be updated to reflect these Changes.

Unfortunately it's still logging most twice like the screenshot above

**Comment by tetsuo55** [comment]
Ok so this is the issue.

Thermal comfort has humidity A and temperature B.
New temperature value C is received.
Calculate absolute humidity using C and A.
A few milliseconds later the new humidity D is received.
Calculate absolute humidity using C and D,
Repeat.

The solution might be to anticipate this delay, for example.by waiting one second after a new value is received before doing the calculation.

Alternatively, we could cache the sensor value and calculate the absolute humidity once per scan interval, like for example 60 seconds.

I think that last solution is best we it users could set the delay they wanted, with 0 being the current behavior and higher being the behavior I want

**Comment by lymanepp** [comment]
> Oof that was a breaking change, had to rename all the sensors, the new naming seems better tho, readme will have to be updated to reflect these Changes.

That change was unintentional and has been reverted. Sorry x2.

**Comment by lymanepp** [comment]
I committed a change that should reduce the number of updates. It suppresses updates when the value hasn't changed. And it suppresses updates when the change was less than 0.1°C.  The change threshold is configurable.

**Comment by tetsuo55** [comment]
This update really had a huge impact, however i think there is a new issue now.

Looking at the logs the sensor is suppressing changes under 0.1, however it's doing that on the previous value received and not the previous value used to calculate the current absolute humidity.

Aknwha

**Comment by lymanepp** [comment]
> This update really had a huge impact, however i think there is a new issue now.
> 
> Looking at the logs the sensor is suppressing changes under 0.1, however it's doing that on the previous value received and not the previous value used to calculate the current absolute humidity.
> 
> So what just happened is that humidity was rising in one room, with less than 0.1% per update but over time it added up to 2% and then it had one update over the 0.1 threshold and the new absolute humidity was calculated.
> In time this was almost 30 minutes if no new updates from the thermal sensor while the absolute humidity had changed quite a bit

It compares the current value of the calculated sensor with the last saved value. It doesn't save the value if it's less than the threshold, so every comparison should be against the value displayed in HA. So it won't tell HA about a change to dew point if it didn't go up by 0.1°C.

```
        if (
            isinstance(new_state, float)
            and isinstance(self._state, float)
            and abs(new_state - self._state) < self._change_threshold
        ):
            return False

        self._state = new_state
```

**Comment by tetsuo55** [comment]
![IMG_20210924_231152](https://user-images.githubusercontent.com/15817790/134740218-bc7e9511-6255-4bce-a74a-16731cc0c550.jpg)
![IMG_20210924_231117](https://user-images.githubusercontent.com/15817790/134740234-39fcb863-a981-4b71-9452-3d2079c58c88.jpg)
![IMG_20210924_231042](https://user-images.githubusercontent.com/15817790/134740243-e30ebcd7-e7d4-4b72-a337-527539f27507.jpg)

**Comment by lymanepp** [comment]
Your temperature was dropping while the relative humidity rose. It's plausible that the absolute humidity wasn't actually changing. Do you have a sensor for the dew point?

**Comment by tetsuo55** [comment]
![IMG_20210924_232509](https://user-images.githubusercontent.com/15817790/134741396-07f91097-bcc9-4fe4-ad5d-2301708b6c21.jpg)

**Comment by lymanepp** [comment]
As expected, the plots are shaped the same as they're both measuring quantity of water in the air.

**Comment by tetsuo55** [comment]
Awesome this is actually better than i was expecting then, great work!

**Comment by lymanepp** [comment]
Do you still think there's a problem? If so, we'll need to enable debug logging.

```
logger:
  default: info
  logs:
    custom_components.thermal_comfort.sensor: debug
```

**Comment by tetsuo55** [comment]
Thanks I'll look at it for a day or so to see if there is one or not.
But based on what we discussed above it's probably working properly

**Comment by lymanepp** [comment]
> Awesome this is actually better than i was expecting then, great work!

What % reduction did you see? IIRC, you said it was previously ~80% of all values.

**Comment by lymanepp** [comment]
FWIW, I played around with trying to reorder the temperature and humidity updates. But the values seemed pretty flaky even coming from the same sensor. Maybe the sensor is suppressing unchanged values.

**Comment by tetsuo55** [comment]
> > Awesome this is actually better than i was expecting then, great work!
> 
> What % reduction did you see? IIRC, you said it was previously ~80% of all values.

It will take a few days to clear out the database, but what I'm seeing now:
Went from multiple updates every few minutes to 30-60 minute intervals

**Comment by lymanepp** [comment]
>  Went from multiple updates every few minutes to 30-60 minute intervals

Unless the climate is very stable, 30-60 minute intervals is much longer than I'd expected.

**Comment by tetsuo55** [comment]
Maybe 0.1 is too high and i should try 0.05 or maybe even 0.01.

Lots of suppression logs

`2021-09-24 23:52:00 DEBUG (MainThread) [custom_components.thermal_comfort.sensor] Suppressed Master Absolute Humidity update less than 0.1 - new: 11.983082849366976 current: 11.974060879584153`

That precision tho lol
